### ISSUE TITLE
Missing the details on the release process.

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#1]
To release this training:

* Creating the participants guide
* Creating the instructor guide
* Packaging the materials
* Where to deliver the materials

Those details should be captured in the README to ensure that it anyone can walk through this release process.

**Comment by burtlo** [comment]
This video on how to export the content should be in the README: https://drive.google.com/file/d/0B4WmSTt8VtdKZDY5RnhIWVVYZkk/view?usp=sharing

**Comment by SteveDelFante** [comment]
Added link to  video on how to export the content.

**Comment by SteveDelFante** [comment]
Didn't meant to close this issue.
