### ISSUE TITLE
Add file context to slide 7-42

### ISSUE THREAD

**Issue by kennonkwok** [chef-training/chef-essentials#105]
I think we should put the rest of the file in or otherwise indicate that we're only changing the file resource to a template resource and leaving the package/service resources alone.

**Comment by burtlo** [comment]
<img width="1920" alt="screen shot 2015-11-05 at 1 24 49 pm" src="https://cloud.githubusercontent.com/assets/244426/10979177/9cda3da2-83c0-11e5-8218-1b8d82e00a1a.png">

**Comment by burtlo** [comment]
I agree with you. Bringing back to context.
