### ISSUE TITLE
Module 1 Slide 6  Rackspace doesn’t belong there

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-essentials#110]
job Cool cool. So on slide 6 of the Intro deck, we say "Chef can integrate with cloud-based platforms such as Rackspace and Amazon Elastic Compute Cloud to automatically provision and configure new machines.”
​[5:04 PM] 
As much as it pains me as an ex-Racker, Rackspace doesn’t belong there, IMO.
​[5:04 PM] 
AWS + VMware are the two biggest virtualized platforms we’ll come across.	(edited)
​[5:05 PM] 
I think that we should change it to reflect the most common platforms we see customers executing against.
​[5:09 PM] 
Since VMware is a hairy mess, maybe Azure would be a more suitable substitution for Rackspace; but I’d say that they’ve given up the dream of being a major public cloud provider http://www.rackspace.com/en-us/managed-aws :simple_smile:
​[5:09 PM] 
They being RAX
​[5:25 PM] 
scar Yes update it with azure pls

**Comment by burtlo** [comment]
<img width="737" alt="2015-12-14_12-21-03" src="https://cloud.githubusercontent.com/assets/244426/11789641/26b12da0-a25d-11e5-91a3-7beb039310ef.png">

Changed to Azure and AWS in commit 4da583bf4919cb00c10a3bbe821169eadddd64e1
