### ISSUE TITLE
Module 2 Slide 38 - Green highlighting incorrect position

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials#112]
Reposition the green highlighting (move up one line) to cover mode through action

**Comment by burtlo** [comment]
Before:

<img width="648" alt="2015-12-14_12-24-06" src="https://cloud.githubusercontent.com/assets/244426/11789715/94f40b2a-a25d-11e5-8810-41b68066a9f2.png">

After:

<img width="648" alt="2015-12-14_12-24-07" src="https://cloud.githubusercontent.com/assets/244426/11789721/9ca77e1a-a25d-11e5-9665-daafaf82d868.png">
