### ISSUE TITLE
Module 12 Slide 8 - Roles directory exists; slide unnecessary

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials#120]
Students regularly point out the slide is incorrect as chef gem generate cookbook creates the roles directory. Why not just remove the slide?

**Comment by burtlo** [comment]
The starter kit does indeed have this directory so I will remove it from the slides.

**Comment by burtlo** [comment]
Actually I will leave it. The comment that the instructor is suggested to use and the ones that the learner will read says: "Create a roles directory if necessary. If you are using the Chef Starter Kit this directory may already exist."
