### ISSUE TITLE
Module 14 Slide 11 - Environments directory exists

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials#121]
The chef generate cookbook command used earlier creates the environments subdirectory. Students point out the directory already exists -- why bother with slide? Why not delete?

**Comment by burtlo** [comment]
`chef generate cookbook` generates the cookbooks on the first day and does not generate an environments directory. On the second day the learner has been asked to download a starter kit and use that. That directory does not have an environments sub-directory so it is still necessary to be created.
