### ISSUE TITLE
Module 2 Slide 42 - Output missing data

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials#122]
v1.0.3
Prior slide shows four packages in recipe but output on this slide shows only two being applied. Two missing packages should be added to output (flagged by observant students)

**Comment by burtlo** [comment]
<img width="649" alt="2015-12-14_12-35-07" src="https://cloud.githubusercontent.com/assets/244426/11790150/d3d3d602-a25f-11e5-8b2f-45dcd76df159.png">
