### ISSUE TITLE
Module 5 Slide 22 - Kitchen List Table

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials#123]
v1.0.3
Kitchen list output is missing multiple columns of data.
The verifier and transport columns of info should be added (flagged by students in class)

**Comment by burtlo** [comment]
I updated to add the other columns.

<img width="650" alt="2015-12-14_14-25-36" src="https://cloud.githubusercontent.com/assets/244426/11792965/9e754ec8-a26e-11e5-8cf7-8538962dae85.png">

I also then fixed the bars and formatting

<img width="893" alt="2015-12-14_14-25-37" src="https://cloud.githubusercontent.com/assets/244426/11792981/b01ad030-a26e-11e5-8f71-987813d511c6.png">
