### ISSUE TITLE
Feedback from a Recent Delivery of the Content

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#127]
Shared by Jessica DeVita and Jody Wolfborn:

Essentials Slide Notes

* [x]	Slide 1-8, remove Backspace
* [x]	Slide 2-14 “This company” should be “This computer”
* [x]	Slide 2-16 doesn’t say which type of example it is: “GE” and “Labs” not on every slide? 
* [ ]	Slide "Desired Configuration”, change “environs” to “environments”?
* [ ]	Slide 2-21, combine with previous slides? redundant
* [ ]	Slide 2-40, add “package ‘vim’” and “package ‘emacs’”
* [ ]	Slide 3-8, why is there a line break between “package ‘emacs’” and “package ‘tree’”?
* [x]	Slide 3-17, why is “recipes” highlighted, when it’s talking about the README?
* [x]	Slide 3-22, why are there two README.md files? Also a .gitignore file?
* [ ]	Slide 3-15 to 3-25 - Discuss weirdness on slides
* [ ]	Slide 3-35, add “Use chef generate recipe” to the “create a recipe” portion
* [x]	Slide 3-37, confusing that it says “modify the Apache Recipe” rather than “server.rb” recipe
* [x]	Slides 3-39 through 3-41 have the wrong slide numbers
* [x]	Slide 3-41, add “you” to “How often would *you* commit”
* [x]	Slide 4-12, add “s” to final “Cookbook” (also, maybe talk a little about the syntax “mv workstation cookbook”?)
* [x]	Slide 4-14
* [x]	Slide 4-20, add # before “reserved”
* [x]	Slide 5-25, explicitly say “edit kitchen.yml”?
* [x]	Slide 5-29, 5-30, 5-39 and 5-40, either add more info about the “[INSTANCE…]” to talk track or remove from the slide
* [x]	Slide 5-36, update to be more clear on what it’s asking, etc.?
* [ ]	Slide 5-40, specify which cookbooks you should be kitchen destroy-ing
* [x]	Slide 5-42, “software” instead of “softwares”
* [x]	Slide 5-44, remove “s” from “Test Helper Tools”
* [x]	Slide 5-55, update this to remove the sentence fragments, change “Event” to “Even”
* [x]	Slide 5-60, add the rest of the packages that are installed in the Workstation::setup (vim, emacs, nano, and /etc/motd?)
* [x]	Slide 5-61 and 5-62, make sure it’s clear that they need to be in the workstation directory
* [x]	Slide 5-25 and 5-26, implies that everything below “run_list” should be deleted; talk-track should make it clear that the “workstation::default” is still part of the run list
* [x]	Slide 6-35, clarify whether you’re supposed to delete the various package commands?
* [ ]	Slide 6-36, how to test that the variable is being passed appropriately?
* [x]	Slide 6-39, “Lets” should be “Let’s”
* [x]	Slide 7-4, why is “httpd” changed to “apache2”?
* [x]	Slide 7-8, why are we “escaping our feelings”?
* [x]	Slide 7-16, is this a demo or an example?
* [x]	Slide 7-21 to 7-23, why are we going over this information again??? We’ve already used “chef generate”
* [ ]	Slide 7-36, can pass any Ruby into Angry Squid? Can you use Angry Squid in Recipes? “Pretty much, yup”,
* [x]	Slide 7-42, add “Resource” after “Template” (otherwise confusion as to whether we’re actually converting the file to a template)
* [x]	Slide 7-35, make it more clear that we’re supposed to update the index.html.erb to have the “hello, world” text from the server.rb
* [ ]	Slide 7-50, call out explicitly what the -s is trying to do, and find out why there’s not a -s in the apache template creation
* [ ]	Slide 7-50, can we change the source from the actual file to be the setup.rb recipe instead?
* [ ]	Slide deck for Chapter 8 is not available in Word format?
* [ ]	Slide 9-15, Why talk about conEmu?
* [ ]	Slide 9-29, “knife client list” needs to be run from chef-repo directory
* [x]	Slide 10-37, is there an unnecessary colon between “recipe” and the bracket?
* [ ]	Slide 10-25, we taught them how to use variables, these slides shouldn’t be hard-coded
* [ ]	Slide 10-32, should call out explicitly that versions don’t match what they’ve coded on their haproxy settings
* [ ]	Slide 11-12, widen the page in order to increase font size to something readable and make this variables rather than hard-coded
* [x]	Slide 11-12, ‘ipaddress' should be an IP address, rather than the hostnames
* [x]	Slide 12-8, setting up the starter kit on Windows servers automatically creates a roles directory within the chef-repo directory; add “IF NEEDED” to title
* [x]	Slide 12-9, why do we call this “proxy" instead of “load_balancer"?
* [x]	Slide 12-14, put all the text on the same line?
* [ ]	Slide 12-27, talk track doesn’t explain nested roles or what the right answer is
* [x]	Slide 13-4, typo on talk-track “add them TO a list”
* [ ]	Slide 13-5, node numbers are incorrect; seems to indicate way more machines than we provide trainees
* [x]	Slide 13-11, typo in talk-track “we ask about A specific attribute”
* [x]	Slide 13-20, provide a gist with final recipe
* [x]	Slide 13-29, talk track doesn’t explain what’s meant by “terminate a node without removing it”
* [x]	Slide 14-2, should say “create an acceptance and a production environment”
* [x]	Slide 14-4 and 5, typo in box refers to Node 8 (node 1&2 to prod and 3 to acceptance)
* [x]	Slide 14-6 and 7, font is too small
* [x]	Slide 14-12, “create a new environment file” to be consistent with language on slide for creating an acceptance environment”
* [x]	Slide 14-16, add highlighting to be consistent with other slides
* [x]	Slide 14-49, no talk track for these questions
* [x]	Slide 14-50, typo “what happens when you USE and in a query”; talk track, what example should we provide here?

**Comment by burtlo** [comment]
```
Slide 2-21, combine with previous slides? redundant
```

The graph the represents test and repair is redundant. This is done to help people visualize the decision tree that is taking place within the code base.

**Comment by burtlo** [comment]
```
Slide 2-40, add “package ‘vim’” and “package ‘emacs’”
Slide 3-8, why is there a line break between “package ‘emacs’” and “package ‘tree’”?
```

We are asking the learner to install one editor their own editor of choice. The inclusion of all the editors in the answer is to show them all the possible range of responses. That is also why I chose to put the space between all the packages that install editors and the package that installs tree.

**Comment by burtlo** [comment]
The remaining unchecked items were not fixed because they are questions raised about the content, could not be mapped to the particular slide specified,

**Comment by burtlo** [comment]
```
Slide 3-35, add “Use chef generate recipe” to the “create a recipe” portion
```

We could teach that here but we are asking them to complete an lab exercise so I choose often not to introduce new concepts. If we had done it before for a particular reason in the group exercise I would definitely make that change.

**Comment by burtlo** [comment]
```
Slide 5-40, specify which cookbooks you should be kitchen destroy-ing
```

I updated the first slide that talks about the `[INSTANCE|REGEXP|ALL]` to give more examples. I am not sure for the destroying if there is more information on the destroy.

**Comment by burtlo** [comment]
```
Slide 6-36, how to test that the variable is being passed appropriately?
```

We aren't really passing variables when we use them within the string using the string interpolation. The best way would be to test that they are present in the file in the integration test. In interest of time we don't go into that it. Sometimes when I teach that content I go into writing that test using the file matchers and talk about using a regular expression with the website [Rubular](http://rubular.com/).

**Comment by burtlo** [comment]
```
Slide 7-36, can pass any Ruby into Angry Squid? Can you use Angry Squid in Recipes? “Pretty much, yup”,
```

Anywhere within a template you can use the angry squids to display the results of any ruby that you want to write in between those tags. I have not used them in a recipe. The preferred way of using variables or ruby code within an recipe is with string interpolation.

**Comment by burtlo** [comment]
```
Slide 7-50, call out explicitly what the -s is trying to do, and find out why there’s not a -s in the apache template creation
Slide 7-50, can we change the source from the actual file to be the setup.rb recipe instead?
```

I think that you may have a different version of the deck or have used different slides. The `chef generate template` command does allow you to specify a flag `-s` that allows you to specify the source of the template. It seems like another way that it could be done to get the base information in the file to start from before adding the angry squid tags. I don't mind either way on this one except we haven't taught them the `-s` flag.

**Comment by burtlo** [comment]
```
Slide deck for Chapter 8 is not available in Word format?
```

I believe that module / chapter 8 now exists.

**Comment by burtlo** [comment]
```
Slide 9-15, Why talk about conEmu?
```

The version of slides that I have never talk about conEmu. I believe you might have a different version of the deck.

**Comment by burtlo** [comment]
```
Slide 10-25, we taught them how to use variables, these slides shouldn’t be hard-coded
```

I purposefully have the learners hard-code the values and then we address that in a later section. My assumption is that it is important to do it wrong the first time, run it, see it work, and then refactor it. However, as a facilitator of the content you are always allowed to deviate from the content to suit your audience.

**Comment by burtlo** [comment]
```
Slide 12-27, talk track doesn’t explain nested roles or what the right answer is
```

These discussion questions purposefully don't have answers because I don't believe there is a right answer here. Some people in the training may feel that nesting of roles should never be allowed. Some people may have a rule of one level or two levels. I like hearing the conversations that come up and offering my opinion on the matter but preface it with my personal opinion.

**Comment by burtlo** [comment]
```
Slide 13-5, node numbers are incorrect; seems to indicate way more machines than we provide trainees
```
<img width="733" alt="2015-12-14_17-14-08" src="https://cloud.githubusercontent.com/assets/244426/11797069/29127314-a286-11e5-9fc2-e8615a527719.png">

I tend to agree that the additional nodes that are present in the list may be confusing for learners.

@SteveDelFante should probably address this one or answer this one. He chose to fill the result sets with more than the existing list of nodes.

**Comment by ubergeekgirl** [comment]
re: Slide 9-15, Why talk about conEmu?
this is because we used the food-trailers machines as a jumpbox and have them use conemu - no need to mention in this material.

**Comment by ubergeekgirl** [comment]
re Slide 7-50, and the -s   I think the issue was that it just didn't work as expected, it didn't copy it. I won't worry about it for now, unless others are having the same issue.

**Comment by ubergeekgirl** [comment]
re: Slide 10-25  and the hard-coding. I prefer to use that time to reinforce using the ohai. I can show them the slide but ask them not to type those things manually. I think it's very frustrating to the learner otherwise. But yes leave it open to the instructor.
