### ISSUE TITLE
Resource Module - Asking Learners to Read the Documentation De-Values the Course

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#144]
> In Chef Fundamentals we talk about the Principle of Least Surprise and also that Chef conventions employ the "Most common positive action" as the default. But here it seems to be pushing people to read the documentation. This idea of pushing people toward the docs is repeated throughout the course. In my view this de-values the course and most probably will annoy students. Students do not want to be told to 'read the manual', and come on courses not just to understand what commands to use, but also to understand why things work the way they do.

**Comment by SteveDelFante** [comment]
Learning where to find info in the docs is a good component in technical training, IMO.

**Comment by ehaselwanter** [comment]
There is real value in pointing participants to docs.chef.io. We should definitely make that a development 'workflow' thing. I always strongly suggest to have the docs pages open for example uses and default settings of resources

**Comment by burtlo** [comment]
Sounds like those of us here are in agreement. I will close this issue.
