### ISSUE TITLE
Add Platform to Cover Page for Instructor / Participant 

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#152]
This content is based on CentOS.

**Comment by SteveDelFante** [comment]
Should we not label the cover "Chef Essentials for Linux"? (Rather than CentOS)? I think it would then align with  "Chef Essentials for Windows" plus the customer-facing course titles on the web are "Chef Essentials for Linux" and "Chef Essentials for Windows".

**Comment by burtlo** [comment]
It's not Linux. It's CentOS.  This content would not work on Ubuntu which is also Linux.

**Comment by burtlo** [comment]
One time we taught a class for a company that was SuSE Linux. In the future we may teach one again in Ubuntu. The examples will need to change in those situations. I'm worried if we say Linux. I'm fine advertising it that way. On the cover it might be better to be more clear about the flavor of OS.
