### ISSUE TITLE
Essentials 1.0.4, slide 9-21 and 9-22 point to a URL that redirects to a different github repo

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-essentials#156]
In essentials 1.0.4, slide 9-21 and 9-22 point to a URL that redirects to a different github repo... caused some confusion for students... we should correct that... 

Larry reported this. I have not tested it all yet,

**Comment by burtlo** [comment]
It redirects to https://github.com/chef-training/chef-essentials-repo. That is true, it needs to be updated.

**Comment by ehaselwanter** [comment]
yep. that was confusing for me too. it definitely works with the chef-essentials repo. another option would be to introduce `scp` to copy the developed work? it _should_ be in a workable state anyways.

**Comment by burtlo** [comment]
@ehaselwanter they could also use git to transport it off the system.

**Comment by burtlo** [comment]
Fixed in commit 9860ebba912a652acd21060b326ad0fede570307
