### ISSUE TITLE
chef-client (module 4) slides 22 and 26 need to cd to ~/cookbooks/workstation and ~/cookbooks/apache

### ISSUE THREAD

**Issue by binamov** [chef-training/chef-essentials#157]
Module 4 introduces `chef-client --local-mode` and to make that work a `cookbooks` folder is created in `~` and the `workstation` with the `apache` cookbooks are moved to this new location.

Slides 22 and 26 instruct participants to `cd` into the respective cookbook folders in order to `git add .` and `git commit` the new code.

The participants' `pwd` (present working directory) at the time of execution of those steps is `~` (as per slide 10) and hence the path to the cookbook folders is now within the `~/cookbooks` folder. Running `cd workstation` and `cd apache` (as currently instructed) will not work.

Hence slide 22 should be changed from `cd workstation` to `cd cookbooks/workstation` or `cd ~/cookbooks/workstation`. Slide 26 should be similarly changed to indicate the full/relative path to the `apache` cookbook as well.

**Comment by ehaselwanter** [comment]
this path jumping is rather confusing. maybe we should tell participants to open another terminal at the top level for the `chef-client --local-mode` part and stay in the cookbooks folders for the local development?

**Comment by burtlo** [comment]
When you teach it you definitely can tell them to open another terminal. In the training we could generate a slide with a different look to represent that terminal but I'm hesitant as it is often difficult for learners to remember their various terminals or locations where they should be executing the command.

In the past the suggestion has been to show the current working directory somewhere on the slide to ensure they know where they are at when executing the comand.
