### ISSUE TITLE
Remove the hosted chef piece from the actual class

### ISSUE THREAD

**Issue by reverest66** [chef-training/chef-essentials#163]
When we send them the confirmation email we list a number of things that students need to do to prepare for the class.  "Download the ChefDK, make sure you have an editor.  Here are your linux prereqs."  I think another thing we could have them do ahead of time is to set up their hosted chef account.  This takes a lot of class time.

I have been having my students do this as "homework" before they come in on day 2 - and it has reduced class time by quite a lot.  I have more time for Question/Answer and for dealing parking lot issues and hack sessions.  Basically, for the Chef Server module, I have them do everything up to the "Knife" slide, and then we start there the next day.  It's been working great!

**Comment by burtlo** [comment]
That sounds great!

I would not suggest we remove it and suggest instead you skip it when it comes time to present it.
