### ISSUE TITLE
Remove the Install-Fest module 

### ISSUE THREAD

**Issue by reverest66** [chef-training/chef-essentials#164]
In our confirmation email we are telling students to download the Chef DK.  They do this ahead of class.  I don't think we need this module at all.  We could keep it and provide it to students if necessary, but I have been skipping it completely, and the class has gone very smoothly.  No one has had ChefDK issues in my classes.

**Comment by SteveDelFante** [comment]
Shouldn't we leave it in in case they don''t install ChefDK? Then you can skip it if they have? Otherwise we have lots of renumbering modules, editing course descriptions, web sites,  etc.

**Comment by burtlo** [comment]
@reverest66 I am with @SteveDelFante. If they have everything installed then skip the module.

Also, even if people install the ChefDK it may not work correctly. I allow that time to help troubleshoot anyone's workstation. I have come back in on the second day and found that some workstations did not correctly have the paths defined. It was much better to find that out at the end of the first day and not the beginning of the second day
