### ISSUE TITLE
Commit messages do not adhere to beat practices

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#169]
The commit messages do not adhere to best practices. http://chris.beams.io/posts/git-commit/

**Comment by mattstratton** [comment]
This issue title does not adhere to the best practice of the spelling of the word "best".

**Comment by burtlo** [comment]
@mattstratton 
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjN5ubSqI7LAhUhsIMKHaXGDjAQjRwIBw&url=http%3A%2F%2Fwww.priscillawoolworth.com%2Fcontent%2Feco-garden-august-2011&psig=AFQjCNEVA6PiCi7uRjWzwEw6YOiKrgi84w&ust=1456331740449892
