### ISSUE TITLE
Resource Module - Slide 2-14 - Typo

### ISSUE THREAD

**Issue by slashterix** [chef-training/chef-essentials#172]
In the example code it says `computer` and in the text below it says `company`. Issue is also in the word doc text.

**Comment by burtlo** [comment]
Thank you.

**Comment by burtlo** [comment]
<img width="737" alt="2016-02-26_21-04-06" src="https://cloud.githubusercontent.com/assets/244426/13370434/95064fca-dccc-11e5-821e-61494693f0ed.png">

**Comment by slashterix** [comment]
Word doc `02-Resources.docx
` also needs updating to match the slide.

**Comment by burtlo** [comment]
@slashterix we usually update the doc when we get closer to releasing. Only because the Powerpoint to Word takes quite a bit of effort. We batch up the changes.
