### ISSUE TITLE
hello.rb recipe writes to root directory

### ISSUE THREAD

**Issue by nedward** [chef-training/chef-essentials#175]
By moving from chef-apply to the chef-client it exposed a slightly different behavior: When the student execute: `chef-client --local-mode setup.rb` The chef-client writes the hello.txt file to the root directory, which will cause confusion as the next step has them `cat hello.txt` from the chef home directory where it will not be found.

The old chef-apply command would write the file in the directory the command was executed so it makes sense how this could be overlooked.

**Comment by ehaselwanter** [comment]
I did use this fact to explain the different user context of `sudo chef-client`
