### ISSUE TITLE
Inconsistent 'chef-essentials-appendix-z' docs

### ISSUE THREAD

**Issue by johnfitzpatrick** [chef-training/chef-essentials#177]
The file `PDFs > Instructor Guide > chef-essentials-appendix-z.pdf` is different from `chef-essentials-appendix-z.docx` in the root dir.  If they used one in PDF dir they'd spin up the wrong verion of the AMI. Not sure what other  diffs there are.

**Comment by SteveDelFante** [comment]
Hi John, They both appear to be specifying Essentials - CentOS 6.7 - 5.0.0. Or maybe I need some coffee?

**Comment by SteveDelFante** [comment]
Not an actual issue.
