### ISSUE TITLE
Update verbiage to reflect modern resource descriptions

### ISSUE THREAD

**Issue by eeyun** [chef-training/chef-essentials#182]
Multiple times throughout the deck (when referring to 'resources') we are still printing 'resource attributes' rather than 'resource properties'. After Chef 12.5 and the release of custom resources we have changed all internal verbiage (including blog posts on custom resources) to refer to 'resource attributes' as 'resource properties' .

Essentially we need to s/resource attributes/resource properties. I don't have time currently to hunt down the specific slides but when I get a moment I will attempt to update the issue.

**Comment by burtlo** [comment]
This is correct.
