### ISSUE TITLE
Create Test Kitchen Handout

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials#67]
<img width="830" alt="screen shot 2015-10-05 at 11 17 14 am" src="https://cloud.githubusercontent.com/assets/244426/10286283/acab87a8-6b52-11e5-9609-c267c17dccdb.png">

I think that this image would make a great single page sheet for the learner. 

We may also want to include:

* More details about the commands
* More details about the configuration fields
* Platforms and Suites generating the Test Matrix
* Diagramming the Test Kitchen file path
* Spec / ServerSpec language diagram
* ServerSpec examples

**Comment by SteveDelFante** [comment]
I added this handout to the instructor kit.
